### ISSUE TITLE
Make binding with Travis CI and Gerrit

### ISSUE THREAD

**Issue by haskone** [NODCode/nodcode#1]
- add a minimal config file for travis-ci
- provide a minimal test commit with gerrit

travis-ci.org
gerrithub.io

**Comment by azulw9** [comment]
We will use Codacy for code reviewing. And I have already connected our project with Travis-Ci and added Codacy in Git.
@NODCode/devs

**Comment by azulw9** [comment]
Maybe you'll need to sign in on next sites: https://www.codacy.com/ and https://travis-ci.org/ with login and password from Git.
@NODCode/devs

**Comment by azulw9** [comment]
@haskone, What do you mean "Commit a base README"? issue #9

**Comment by haskone** [comment]
@azulw9 So it's a separate task which is described in #9 but depends on this task =)
I think it's good to have something README with information about directories and files in our project. Sure it's need to be done only when we will start coding

**Comment by azulw9** [comment]
@haskone  OK, I understand. 
@NODCode/devs I think, we can close this issue and return to work with Travis-CI and Codacy in future, when we have some files with code in our repository  :-)
