### ISSUE TITLE
Create Slack room and connect to Travis CI

### ISSUE THREAD

**Issue by chinskiy** [NODCode/nodcode#14]

**Comment by azulw9** [comment]
Must I create Slack room?

**Comment by azulw9** [comment]
And I have already connected our project to Travis-ci. But we haven't any code to test. So I don't understand this task.

**Comment by chinskiy** [comment]
Yes, create new Slack room and connect it to Travis CI. @haskone says that it would be helpful.
I mean https://docs.travis-ci.com/user/notifications/#Slack-notifications

**Comment by haskone** [comment]
It will be useful, especially if (when?) we will use slack for chatting.

**Comment by azulw9** [comment]
@chinskiy, @haskone -  OK. Now we have our Slack chat. And one room "travisci-result" is for results of tests. So, I wait for your emails. https://nodcode.slack.com/messages
@h-ann, Send me your email))

**Comment by chinskiy** [comment]
Cool! I think we can close this Issue.

**Comment by h-ann** [comment]
aniahulita@gmail.com
