### ISSUE TITLE
Add repository APIs description

### ISSUE THREAD

**Issue by haskone** [NODCode/nodcode#17]
Repository Level has to using AMQP for communicate with others components.
So, need to describe how exactly RL will does that

**Comment by h-ann** [comment]
RabbitMQ speaks AMQP 0.9.1, which is an open, general-purpose protocol for messaging. There are a number of clients for RabbitMQ in many different languages. In this project we use Pika, which is the Python client recommended by the RabbitMQ team.

**Comment by h-ann** [comment]
Also call Pika from Tornado.

**Comment by haskone** [comment]
Completed
