### ISSUE TITLE
Description of the project on a wiki page

### ISSUE THREAD

**Issue by haskone** [NODCode/nodcode#2]
- Add a project vision that is based on discussions and similar projects
- Add minimal use cases that are based on the same

**Comment by azulw9** [comment]
There is some Vision on Wiki. Wait for your comments. https://github.com/NODCode/nodcode/wiki/Vision

**Comment by haskone** [comment]
Looks good. At least for now.
About use cases: I propose to make only text use cases (without any pretty diagrams) and make it for the next cases:
- registration / guest mod
- create / delete documents
- add / remove other people with 3 possible permissions: only watch / comments (like comments in google-docs) / edit.

@NODCode/devs  please add your ideas here

**Comment by azulw9** [comment]
@haskone, I agree with idea of text use cases.

**Comment by azulw9** [comment]
So, let's review my use case diagrams: https://github.com/NODCode/nodcode/wiki/Use-case-diagrams-(beta) - @NODCode/devs, wait for your comments.

@haskone, I create an image, too.

**Comment by haskone** [comment]
@azulw9 okay, but I mean more formal usecases (see slack-chat). It's not required but more useful I guess. Anyway, @Likable2707 can doing something for #13 start this point.

**Comment by azulw9** [comment]
@NODCode/devs , here are new use cases :  https://github.com/NODCode/nodcode/wiki/Use-cases----anonymous-messaging-(beta)-_current

wait for comments and remarks

**Comment by azulw9** [comment]
Vision: https://github.com/NODCode/nodcode/wiki/Vision-for-anonymous-messaging-_current
@NODCode/devs
