### ISSUE TITLE
Investigation into RabbitMQ 

### ISSUE THREAD

**Issue by azulw9** [NODCode/nodcode#22]
1. Create a RabbitMQ cluster with 3 nodes on local machine.
2. Tune nodes to synchronise automatically.
3. Create an instruction/script: how to configure this cluster on Linux.

**Comment by chinskiy** [comment]
#22 and #4 possibly duplicates?
@NODCode/devs do we need new task for continuing investigation into RabbitMQ or reopen this?

**Comment by h-ann** [comment]
We need new task about haw to connect configured RabbitMQ to Tornado and business logic.

**Comment by azulw9** [comment]
need RabbitMQ in docker, so reopen this issue
