### ISSUE TITLE
Connection between Tornado & RabbitMQ &  Business logic

### ISSUE THREAD

**Issue by azulw9** [NODCode/nodcode#23]
1. How to connect to RabbitMQ outside the host (with some public IP)?
2. How nodes will choose new Master node if we stop previous master node? 
3. Can we give public IP to each node, or only to a cluster?
4. In what way RabbitMQ will connect with layer of business logic?

**Comment by azulw9** [comment]
@NODCode/devs , I don't know how to write this task in better way)

**Comment by azulw9** [comment]
1. We can have 2 situations:
   1) rabbitmq on local machine, IP of my machine and different ports for each rabbitmq node, but there are troubles with down/up of master node;
   2) rabbitmq nodes in 3 different docker containers + port mapping - I hadn't checked this variant yet.
2. There are no masters and slaves)
3. IP of local machine and different ports.
4. Layer of BL solves this problem.

**Comment by haskone** [comment]
Already completed
