### ISSUE TITLE
Avatar for the organization 

### ISSUE THREAD

**Issue by h-ann** [NODCode/nodcode#8]
Find funny and nice picture =)

**Comment by chinskiy** [comment]
maybe [this](http://img0.joyreactor.cc/pics/comment/Command-%26-Conquer-%D0%98%D0%B3%D1%80%D1%8B-NOD-%D0%98%D0%B3%D1%80%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B0%D1%80%D1%82-1534200.jpeg) or [this](http://www.motifake.com/image/demotivational-poster/0804/the-brotherhood-of-nod-videogames-nod-demotivational-poster-1208770138.gif) or [this](http://nyerguds.arsaneus-design.com/cncimg/img_archive/fan/nod.jpg)?

@NODCode/devs ideas or voting?)

**Comment by haskone** [comment]
2

**Comment by azulw9** [comment]
@chinskiy ,where you find this scary pictures? I'll try to find some other variants)

**Comment by azulw9** [comment]
Maybe one from this:

[1](https://s-media-cache-ak0.pinimg.com/736x/c2/61/75/c26175a9d4d5ebb649812f6ce6a89eed.jpg)
[2](https://image.freepik.com/free-vector/teamwork-illustration-made-with-gears-and-avatars_1025-440.jpg)
[3](http://chapleau.us/Img/CodeMonkey.jpg)
[4](http://rlv.zcache.com/code_monkey_sticker-r876ea1ed486142b2a5ea82bd41f9040c_v9waf_8byvr_1024.jpg)
[5](http://img.gamebazar.cz/usericons/13200.jpg)

@NODCode/devs , what do you think?

**Comment by azulw9** [comment]
@chinskiy , why not?

**Comment by chinskiy** [comment]
@azulw9 very positive avatars for this world :) 
but could be so

**Comment by chinskiy** [comment]
@azulw9 very positive for this world :) 
but could be so, it's only my opinion

**Comment by haskone** [comment]
@azulw9 : 3 - it's .. pretty enough for presenting/describing our team =)

**Comment by azulw9** [comment]
@haskone , I think so, too))

**Comment by h-ann** [comment]
I don`t have the rules to change the avatar, so @haskone, please, set it and close the issue at least =)

**Comment by azulw9** [comment]
@NODCode/devs , https://github.com/NODCode

Yeap, we did it))
